site_name: Graph Learning Management System
site_description: 'Graph LMS Design Documents All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/graph-lms'
repo_url: 'https://github.com/dmccreary/graph-lms'

nav:
  - Home: index.md
  - About: about.md
  
  - Concepts:
    - Introduction: concepts/index.md
    - Concepts: concepts/concept-graphs.md
    - Content: concepts/content-graphs.md
    - Learning Trajectories: concepts/learning-trajectories.md
    - Experience API (xAPI): concepts/xapi.md
    - Learning Record Store (LRS): concepts/lrs.md
  
  - Architecture:
    - Introduction: arch/index.md
    - Core Systems: arch/core-systems.md
    - TLA: concepts/tla.md
  
  - View Data Model:
    - Introduction: view-data-model/index.md
    - View with Vis.js: view-data-model/view-model.html
  
  - Prompts:
    - Introduction: prompts/index.md
    - Word Cloud: prompts/01-wordcloud/index.md
    - Glossary: prompts/02-glossary/index.md
    - TLA Glossary: prompts/03-tla-glossary.md
    - Pitch Deck: prompts/sample-pitch-deck.md

  - MicroSims:
    - Intro: sims/index.md
    - Sample Architecture Drawing: sims/sample-arch/index.md
    - Graph Integrated Learning Architecture: sims/graph-ila/index.md
    - Templates: sims/templates/index.md
  
  - References: references.md
  - License: license.md
  - How We Built This Site: how-we-built-this-site.md
  - Glossary: glossary.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material

  logo: img/logo-180.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
    - css/extra.css
extra_javascript:
    - js/extra.js
extra:
  analytics:
    provider: google
    property: G-JLDD8032H6