site_name: Graph LMS
site_description: 'Graph LMS Design Documents All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/graph-lms'
repo_url: 'https://github.com/dmccreary/graph-lms'

nav:
  - Home: index.md
  - Concepts:
    - Introduction: concepts/index.md
    - Concepts: concepts/concept-graphs.md
    - Content: concepts/content-graphs.md
    - Learning Trajectories: concepts/learning-trajectories.md
  - Architecture:
    - Introduction: arch/index.md
    - Core Systems: arch/core-systems.md
  - View Data Model:
    - Introduction: view-data-model/index.md
    - View with Vis.js: view-data-model/view-model.html
  - References: references.md
  - License: license.md
  - How We Built This Site: how-we-built-this-site.md
  - Glossary: glossary.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo-180.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX